const PRODUCT_IMAGES={
'DR-001':'assets/dr-001-blackwing.png',
'DR-002':'assets/dr-002-old-earth.png',
'DR-003':'assets/dr-003-thornkeeper.png',
'DR-004':'assets/dr-004-ash-and-amber.png',
'DR-005':'assets/dr-005-night-garden.png'
};
const DEFAULT_PRODUCTS=[
{id:'DR-001',name:'Blackwing',type:'one-of-one',category:'hanging',price:285,status:'available',species:'Animal pelvis',materials:'Bone, cord, beads, feathers',dimensions:'Approx. 36 in overall',description:'A vertically composed hanging work built around an ethically and legally sourced pelvis, webbed cordwork, dark feathers and mixed beads.'},
{id:'DR-002',name:'Old Earth',type:'one-of-one',category:'statement',price:650,status:'sold',species:'Large animal pelvis',materials:'Bone, cord, beads, feathers, natural fur',dimensions:'Large statement scale',description:'A substantial hanging work pairing a large pelvis with long beadwork, feather and fur elements.'},
{id:'DR-003',name:'Thornkeeper',type:'repeatable',category:'hanging',price:145,status:'available',species:'Assorted legally sourced bone',materials:'Bone, cord, glass beads',dimensions:'Varies by natural material',description:'A small-run hanging study. Each example follows the same visual language while preserving natural variation.'},
{id:'DR-004',name:'Ash & Amber',type:'one-of-one',category:'statement',price:420,status:'available',species:'Animal bone assemblage',materials:'Bone, cord, amber-tone beads, fur',dimensions:'Statement scale',description:'Warm earth tones, asymmetrical movement and dimensional webbing built around natural anatomy.'},
{id:'DR-005',name:'Night Garden',type:'one-of-one',category:'hanging',price:325,status:'sold',species:'Animal pelvis',materials:'Bone, black cord, beads, feathers',dimensions:'Approx. 40 in overall',description:'A collected work preserved here as part of the permanent archive.'}
];
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function products(){try{return (JSON.parse(localStorage.getItem('dr_products'))||DEFAULT_PRODUCTS).map(p=>({...p,image:p.image||PRODUCT_IMAGES[p.id]||PRODUCT_IMAGES['DR-001']}))}catch{return DEFAULT_PRODUCTS.map(p=>({...p,image:PRODUCT_IMAGES[p.id]}))}}
let cart=JSON.parse(localStorage.getItem('dr_cart')||'[]');
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
function card(p,archive=false){return `<article class="${archive?'archive-card':'product-card'}" data-id="${p.id}"><div class="product-image"><img src="${p.image}" alt="${p.name} specimen"><span class="badge">${archive?'COLLECTED':p.type==='one-of-one'?'ONE OF ONE':'SMALL RUN'} · ${p.id}</span></div><div class="product-meta"><div><p>${p.species}</p><h3>${p.name}</h3></div>${archive?'':`<strong>${money(p.price)}</strong>`}</div>${archive?`<p>${p.materials}</p>`:''}</article>`}
function render(filter='all'){const all=products();const avail=all.filter(p=>p.status==='available'&&(filter==='all'||p.type===filter||p.category===filter));$('#product-grid').innerHTML=avail.length?avail.map(p=>card(p)).join(''):'<p>No works currently match this cabinet.</p>';$('#archive-grid').innerHTML=all.filter(p=>p.status==='sold').map(p=>card(p,true)).join('')||'<p>The archive is waiting for its first collected work.</p>';$$('[data-id]').forEach(el=>el.onclick=()=>openProduct(el.dataset.id));bindTilts()}
function openProduct(id){const p=products().find(x=>x.id===id);if(!p)return;$('#modal-content').innerHTML=`<div class="modal-layout"><div class="modal-visual"><img src="${p.image}" alt="${p.name}"></div><div class="modal-copy"><p class="eyebrow">SPECIMEN ${p.id} · ${p.status==='sold'?'COLLECTED':p.type.replaceAll('-',' ')}</p><h2>${p.name}</h2><p>${p.description}</p><div class="details"><span>Form<b>${p.species}</b></span><span>Materials<b>${p.materials}</b></span><span>Scale<b>${p.dimensions}</b></span><span>Status<b>${p.status==='sold'?'Collected':'Available'}</b></span></div>${p.status==='sold'?'<button class="btn" disabled>Collected / Archived</button>':`<button class="btn primary" data-add="${p.id}">Add to Bag · ${money(p.price)}</button>`}<p><small>Natural variation, marks and irregularities are inherent to bone and natural materials. US shipping only.</small></p></div></div>`;$('#product-modal').showModal();const add=$('[data-add]');if(add)add.onclick=()=>{addCart(p.id);$('#product-modal').close();openCart()}}
function addCart(id){const p=products().find(x=>x.id===id);if(!p||p.status!=='available')return;if(p.type==='one-of-one'&&cart.includes(id))return;cart.push(id);saveCart()}
function saveCart(){localStorage.setItem('dr_cart',JSON.stringify(cart));renderCart()}
function renderCart(){const all=products();const ps=cart.map(id=>all.find(p=>p.id===id)).filter(Boolean);$('[data-cart-count]').textContent=ps.length;$('[data-cart-items]').innerHTML=ps.length?ps.map((p,i)=>`<div class="cart-item"><span>${p.id} · ${p.name}</span><b>${money(p.price)}</b><button data-remove="${i}">Remove</button></div>`).join(''):'<p>Your bag is empty.</p>';$('[data-cart-total]').textContent=money(ps.reduce((a,p)=>a+p.price,0));$$('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);saveCart()})}
function openCart(){$('.cart').classList.add('open');$('.scrim').classList.add('open');$('.cart').setAttribute('aria-hidden','false')}
function closeCart(){$('.cart').classList.remove('open');$('.scrim').classList.remove('open');$('.cart').setAttribute('aria-hidden','true')}
function bindTilts(){$$('.product-card').forEach(card=>{card.onmousemove=e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.setProperty('--tiltY',`${x*8}deg`);card.style.setProperty('--tiltX',`${y*-8}deg`)};card.onmouseleave=()=>{card.style.setProperty('--tiltY','0deg');card.style.setProperty('--tiltX','0deg')}})}
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduced){const orb=$('.cursor-orb');document.addEventListener('pointermove',e=>{orb.style.left=e.clientX+'px';orb.style.top=e.clientY+'px'});const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('seen');io.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>io.observe(el));window.addEventListener('scroll',()=>{const y=scrollY;$$('.sigil').forEach((s,i)=>s.style.translate=`0 ${y*(.015+(i*.006))}px`)},{passive:true})}else $$('.reveal').forEach(el=>el.classList.add('seen'));
$$('[data-cart-open]').forEach(b=>b.onclick=openCart);$$('[data-cart-close]').forEach(b=>b.onclick=closeCart);$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});$('.modal-close').onclick=()=>$('#product-modal').close();$('.menu').onclick=()=>$('.site-header').classList.toggle('nav-open');$('#commission-form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const leads=JSON.parse(localStorage.getItem('dr_commissions')||'[]');leads.unshift({...data,id:'CR-'+Date.now(),date:new Date().toISOString(),status:'new'});localStorage.setItem('dr_commissions',JSON.stringify(leads));$('.form-status').textContent='Request saved in this prototype. Connect the production backend before launch for real submissions.';e.target.reset()};$('[data-checkout]').onclick=()=>alert('Checkout is intentionally disabled. A payment provider can be connected after the catalog and inventory workflow are approved.');$('#year').textContent=new Date().getFullYear();render();renderCart();